### ISSUE TITLE
Does this tracking extension work with multi-site typo3 installations?

### ISSUE THREAD

**Issue by subnoodle** [DanielSiepmann/tracking#78]
Dear Daniel,
we update a bunch of massive multisite instances to Typo3 10 and came over your extension earlier (test sites and single site instances).
Can you tell us please, if your extension works out of the box with multisite Typo3 installations?
I did not find anything about it in the documentation.

Further, if it does not work, which kinds of efforts would it take to make it multisite-able?

Thank you very much,
Thomas

**Comment by DanielSiepmann** [comment]
Hey Thomas,

thanks for your interest. I didn't had multisite in mind when developing the site. The tracking itself should work without any issue. It just stores dump tracking records on the pages (which are associated to the sites). But dashboard widgets are not aware of Sites and do not provide a way to analyse per site yet.

I've an open issue #46 which would allow you to add "site" as a tag to each record, and filter for sites within dashboards. But that is not finished or merged yet. Have a look at last comment for current state.

So it depends on your requirements whether support is already there. I'd guess a new extractor which adds the site identifier as tag to each tracking record would make sense.

I hope that feedback helps?

Best regards,
Daniel.

**Comment by DanielSiepmann** [comment]
Hey Thomas,

yes exactly. Right now the editor would see overall tracking information, also from other sites.
The new concept introduces the new extractor which can extract information which is then stored with the tracking info (as tag). The widgets can then filter based on those info (tags).
So one could create each widget for each site with configuration to filter tracking info based on tag "site" with value "siteitendifiera". Each user would be allowed to only use and see widgets from his user group.

Doesn't sound to convinient for the integrator. But I guess one could easily generate the necessary configuration within `Services.php` instead of writing down in `Services.yml` (or use yaml anchors).

The extension itself tries to stay open and flexible, instead of coupled to specific use cases. So the extension itself might not be aware of sites, but you could build your extractor which fetches the site identifier based on current accessed page, which will be stored alongside, and use the mechanics.

But all of that will only work once #46 is merged (which will be a breaking change and leading to version 2.x).

**Comment by DanielSiepmann** [comment]
https://github.com/DanielSiepmann/tracking/blob/feature/46-add-flags-feature/Documentation/Tags.rst already exists as first documentation regarding the tags / extractor concept.
I guess sites could make it into the extension itself as it should be pretty simple but useful.

**Comment by subnoodle** [comment]
Dear Daniel, 
i appreciate your fast and detailed reply and suggestions.
I'll take time to digg into it.
This would take a bit time according to the projects timeline.
Cheers, Th.

**Comment by DanielSiepmann** [comment]
I close this question as solved. Feel free to comment again if something is still unclear and I'll re open and try to help again.
